apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "my-todo-list.fullname" . }}
  labels:
    {{- include "my-todo-list.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "my-todo-list.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.pods.annotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "my-todo-list.labels" . | nindent 8 }}
        {{- with .Values.pods.labels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "my-todo-list.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.pods.securityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.targetPort }}
              protocol: TCP
          {{- range .Values.probes }}
          {{- if .enabled }}
          {{ .name }}:
            {{- toYaml .probe | nindent 12 }}
          {{- end }}
          {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
