apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: api-access
spec:
  podSelector:
    matchLabels:
      app: frontend
  egress:
  - to:
    - ipBlock:
        cidr: 203.0.113.0/24
