apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: production-isolation
spec:
  podSelector: {}
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          env: production
