apiVersion: v1
kind: Pod
metadata:
  name: my-configured-pod
spec:
  containers:
  - name: my-container
    image: nginx:1.23.5-alpine
    env:
    - name: DATABASE_HOST
      valueFrom:
        configMapKeyRef:
          name: my-config
          key: database_host
    - name: DATABASE_PORT
      valueFrom:
        configMapKeyRef:
          name: my-config
          key: database_port
