apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: fast-storage
provisioner: kubernetes.io/aws-ebs # Example provisioner
parameters:
  type: gp2
  zones: us-west-1a
reclaimPolicy: Delete
