apiVersion: apps/v1
kind: Deployment
metadata:
  name: secure-todo-app
  namespace: my-namespace
spec:
  replicas: 2
  selector:
    matchLabels:
      app: todo-app
  template:
    metadata:
      labels:
        app: todo-app
    spec:
      serviceAccountName: my-service-account
      containers:
      - name: todo-app-container
        image: multi-stage-todo-app:1.0.0
        securityContext:
          runAsNonRoot: true
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
        ports:
        - containerPort: 3000
        env:
        - name: NODE_ENV
          value: "production"
