apiVersion: policy/v1beta1
kind: PodSecurityPolicy
metadata:
  name: no-root-psp
spec:
  runAsUser:
    rule: MustRunAsNonRoot
  seLinux:
    rule: RunAsAny
  supplementalGroups:
    rule: RunAsAny
  fsGroup:
    rule: RunAsAny
  volumes:
  - '*'
