apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  namespace: my-namespace
  name: no-root-psp-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: no-root-psp-role
subjects:
- kind: ServiceAccount
  name: my-service-account
  namespace: my-namespace
